#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Newline,
    Equals,
    Colon,
    Comma,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    PercentEquals,
    PlusPlus,
    MinusMinus,
    Bang,
    DoubleAmpersand,
    DoublePipe,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    EqualEqual,
    BangEqual,
    Let,
    Fix,
    Echo,
    If,
    Else,
    While,
    Break,
    Continue,
    Identifier(String),
    IntegerLiteral(i64),
    FloatLiteral(f64),
    StringLiteral(String),
    BoolLiteral(bool),
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub position: usize,
}
